=== vezel-dev/celerity/src/generators/Ast/Ast.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://vezel.dev/celerity/Ast"
            elementFormDefault="qualified">
    <xsd:element name="Tree">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Settings">
                    <xsd:complexType>
                        <xsd:attribute name="Namespace" type="xsd:Name" use="required" />
                        <xsd:attribute name="BaseType" type="xsd:Name" use="required" />
                        <xsd:attribute name="NameSuffix" type="xsd:Name" use="required" />
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="Node" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="Token">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                        <xsd:attribute name="Optional" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>

                                <xsd:element name="Tokens">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                        <xsd:attribute name="Separated" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>

                                <xsd:element name="Child">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                        <xsd:attribute name="Type" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Optional" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>

                                <xsd:element name="Children">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                        <xsd:attribute name="Type" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Separated" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>

                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                        <xsd:attribute name="Base" type="xsd:Name" />
                        <xsd:attribute name="Abstract" type="xsd:boolean" />
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== vezel-dev/celerity/src/syntax/Ast.xml
<Tree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="https://vezel.dev/celerity/Ast"
      xsi:schemaLocation="https://vezel.dev/celerity/Ast ../generators/Ast/Ast.xsd">
    <Settings Namespace="Vezel.Celerity.Syntax"
              NameSuffix="Node"
              BaseType="Syntax" />

    <!-- Structure -->

    <Node Name="ModulePath">
        <Tokens Name="Component" Separated="true" />
    </Node>

    <Node Name="Root" Abstract="true" />

    <Node Name="Document" Base="Root">
        <Children Name="Attribute" Type="Attribute" />
        <Token Name="ModKeyword" />
        <Child Name="Path" Type="ModulePath" />
        <Token Name="Semicolon" />
        <Children Name="Declaration" Type="Declaration" />
    </Node>

    <Node Name="Interactive" Base="Root">
        <Children Name="Declaration" Type="Declaration" />
        <Children Name="Statement" Type="Statement" />
    </Node>

    <!-- Attributes -->

    <Node Name="Attribute">
        <Token Name="At" />
        <Token Name="Name" />
    </Node>

    <Node Name="AttributeValue">
        <Token Name="Equals" />
        <Token Name="Value" />
    </Node>

    <!-- Declarations -->

    <Node Name="Declaration" Abstract="true">
        <Children Name="Attribute" Type="Attribute" />
        <Token Name="Name" />
    </Node>

    <Node Name="MissingDeclaration" Base="Declaration">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="Name" Override="true" />
        <Tokens Name="Skipped" />
    </Node>

    <Node Name="UseDeclaration" Base="Declaration">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="UseKeyword" />
        <Token Name="Name" Override="true" />
        <Token Name="Equals" />
        <Child Name="Path" Type="ModulePath" />
    </Node>

    <Node Name="TypeDeclaration" Base="Declaration">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="PubKeyword" Optional="true" />
        <Token Name="OpaqueKeyword" Optional="true" />
        <Token Name="TypeKeyword" />
        <Token Name="Name" Override="true" />
        <Child Name="ParameterList" Type="TypeParameterList" Optional="true" />
        <Token Name="Equals" />
        <Child Name="Type" Type="Type" />
    </Node>

    <Node Name="TypeParameterList">
        <Token Name="OpenParen" />
        <Children Name="Parameter" Type="TypeParameter" Separated="true" />
        <Token Name="CloseParen" />
    </Node>

    <Node Name="TypeParameter">
        <Children Name="Attribute" Type="Attribute" />
        <Token Name="Name" />
    </Node>

    <Node Name="CodeDeclaration" Base="Declaration" Abstract="true">
        <Child Name="Body" Type="Expression" Optional="true" />
    </Node>

    <Node Name="ConstantDeclaration" Base="CodeDeclaration">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="PubKeyword" Optional="true" />
        <Token Name="ConstKeyword" />
        <Token Name="Name" Override="true" />
        <Child Name="Type" Type="TypeAnnotation" Optional="true" />
        <Token Name="Equals" />
        <Child Name="Body" Type="Expression" Override="true" />
    </Node>

    <Node Name="FunctionDeclaration" Base="CodeDeclaration">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="PubKeyword" Optional="true" />
        <Token Name="ExtKeyword" Optional="true" />
        <Token Name="FnKeyword" />
        <Token Name="Name" Override="true" />
        <Child Name="ParameterList" Type="FunctionParameterList" />
        <Token Name="ErrKeyword" Optional="true" />
        <Child Name="ReturnType" Type="ReturnTypeAnnotation" Optional="true" />
        <Child Name="Body" Type="BlockExpression" Optional="true" Override="true" />
    </Node>

    <Node Name="FunctionParameterList">
        <Token Name="OpenParen" />
        <Children Name="Parameter" Type="FunctionParameter" Separated="true" />
        <Token Name="CloseParen" />
    </Node>

    <Node Name="CodeParameter" Abstract="true">
        <Children Name="Attribute" Type="Attribute" />
        <Token Name="Name" />
    </Node>

    <Node Name="FunctionParameter" Base="CodeParameter">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="Name" Override="true" />
        <Child Name="Type" Type="TypeAnnotation" Optional="true" />
    </Node>

    <Node Name="TestDeclaration" Base="CodeDeclaration">
        <Children Name="Attribute" Type="Attribute" Override="true" />
        <Token Name="TestKeyword" />
        <Token Name="Name" Override="true" />
        <Child Name="Body" Type="BlockExpression" Override="true" />
    </Node>

    <!-- Types -->

    <Node Name="Type" Abstract="true" />

    <Node Name="BooleanType" Base="Type">
        <Token Name="BoolKeyword" />
    </Node>

    <Node Name="IntegerType" Base="Type">
        <Token Name="IntKeyword" />
        <Child Name="Range" Type="IntegerTypeRange" Optional="true" />
    </Node>

    <Node Name="IntegerTypeRange">
        <Token Name="OpenParen" />
        <Child Name="LowerBound" Type="IntegerTypeRangeBound" Optional="true" />
        <Token Name="DotDot" />
        <Child Name="UpperBound" Type="IntegerTypeRangeBound" Optional="true" />
        <Token Name="CloseParen" />
    </Node>

    <Node Name="IntegerTypeRangeBound">
        <Token Name="Minus" Optional="true" />
        <Token Name="Literal" />
    </Node>

    <Node Name="RealType" Base="Type">
        <Token Name="RealKeyword" />
    </Node>

    <Node Name="AtomType" Base="Type">
        <Token Name="AtomKeyword" />
    </Node>

    <Node Name="StringType" Base="Type">
        <Token Name="StrKeyword" />
    </Node>

    <Node Name="ReferenceType" Base="Type">
        <Token Name="RefKeyword" />
    </Node>

    <Node Name="HandleType" Base="Type">
        <Token Name="HandleKeyword" />
    </Node>

    <Node Name="ModuleType" Base="Type">
        <Token Name="ModKeyword" />
    </Node>

    <Node Name="LiteralType" Base="Type">
        <Token Name="Minus" Optional="true" />
        <Token Name="Literal" />
    </Node>

    <Node Name="AnyType" Base="Type">
        <Token Name="AnyKeyword" />
    </Node>

    <Node Name="NominalType" Base="Type">
        <Child Name="Path" Type="NominalTypePath" Optional="true" />
        <Token Name="Name" />
        <Child Name="ArgumentList" Type="NominalTypeArgumentList" Optional="true" />
    </Node>

    <Node Name="NominalTypeArgumentList">
        <Token Name="OpenParen" />
        <Children Name="Argument" Type="NominalTypeArgument" Separated="true" />
        <Token Name="CloseParen" />
    </Node>

    <Node Name="NominalTypeArgument">
        <Child Name="Argument" Type="Type" />
    </Node>

    <Node Name="NominalTypePath">
        <Child Name="Path" Type="ModulePath" />
        <Token Name="Dot" />
    </Node>

    <Node Name="RecordType" Base="Type">
        <Token Name="RecKeyword" />
        <Token Name="OpenBrace" />
        <Children Name="Field" Type="TypeField" Separated="true" />
        <Token Name="CloseBrace" />
    </Node>

    <Node Name="ErrorType" Base="Type">
        <Token Name="ErrKeyword" />
        <Token Name="Name" Optional="true" />
        <Token Name="OpenBrace" />
        <Children Name="Field" Type="TypeField" Separated="true" />
        <Token Name="CloseBrace" />
    </Node>

    <Node Name="TypeField">
        <Token Name="MutKeyword" Optional="true" />
        <Token Name="Name" />
        <Token Name="Colon" />
        <Child Name="Type" Type="Type" />
    </Node>

    <Node Name="TupleType" Base="Type">
        <Token Name="OpenParen" />
        <Children Name="Component" Type="Type" Separated="true" />
        <Token Name="CloseParen" />
    </Node>

    <Node Name="ArrayType" Base="Type">
        <Token Name="MutKeyword" Optional="true" />
        <Token Name="OpenBracket" />
        <Child Name="Element" Type="Type" />
        <Token Name="CloseBracket" />
    </Node>

    <Node Name="SetType" Base="Type">
        <Token Name="MutKeyword" Optional="true" />
        <Token Name="Hash" />
        <Token Name="OpenBrace" />
        <Child Name="Element" Type="Type" />
        <Token Name="CloseBrace" />
    </Node>

    <Node Name="MapType" Base="Type">
        <Token Name="MutKeyword" Optional="true" />
        <Token Name="Hash" />
        <Token Name="OpenBracket" />
        <Children Name="Pair" Type="MapTypePair" Separated="true" />
        <Token Name="CloseBracket" />
    </Node>

    <Node Name="MapTypePair">
        <Child Name="Key" Type="Type" />
        <Token Name="Colon" />
        <Token Name="Question" Optional="true" />
        <Child Name="Value" Type="Type" />
    </Node>

    <Node Name="FunctionType" Base="Type">
        <Token Name="FnKeyword" />
        <Child Name="ParameterList" Type="FunctionTypeParameterList" />
        <Token Name="ErrKeyword" Optional="true" />
        <Child Name="ReturnType" Type="ReturnTypeAnnotation" />
    </Node>

    <Node Name="FunctionTypeParameterList">
        <Token Name="OpenParen" />
        <Children Name="Parameter" Type="FunctionTypeParameter" Separated="true" />
        <Token Name="CloseParen" />
    </Node>

    <Node Name="FunctionTypeParameter">
        <Children Name="Attribute" Type="Attribute" />
        <Child Name="Type" Type="Type" />
    </Node>

    <Node Name="AgentType" Base="Type">
        <Token Name="AgentKeyword" />
        <Token Name="OpenBrace" />
        <Children Name="Message" Type="AgentTypeMessage" Separated="true" />
        <Token Name="CloseBrace" />
    </Node>

    <Node Name="AgentTypeMessage">
        <Token Name="Name" />
        <Child Name="ParameterList" Type="AgentTypeMessageParameterList" />
    </Node>

    <Node Name="AgentTypeMessageParameterList">
        <Token Name="OpenParen" />
