=== vezel-dev/celerity/src/generators/Semantics/SemanticTree.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://vezel.dev/celerity/SemanticTree"
            elementFormDefault="qualified">
    <xsd:element name="Tree">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Type" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="Value">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Type" type="xsd:string" use="required" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>

                                <xsd:element name="Node">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Type" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Optional" type="xsd:boolean" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>

                                <xsd:element name="Nodes">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Type" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Separated" type="xsd:boolean" />
                                        <xsd:attribute name="Override" type="xsd:boolean" />
                                    </xsd:complexType>
                                </xsd:element>

                                <xsd:element name="Computed">
                                    <xsd:complexType>
                                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                                        <xsd:attribute name="Type" type="xsd:string" use="required" />
                                        <xsd:attribute name="Body" type="xsd:string" use="required" />
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>

                        <xsd:attribute name="Name" type="xsd:Name" use="required" />
                        <xsd:attribute name="Base" type="xsd:Name" />
                        <xsd:attribute name="Parent" type="xsd:Name" />
                        <xsd:attribute name="Abstract" type="xsd:boolean" />
                        <xsd:attribute name="Root" type="xsd:boolean" />
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== vezel-dev/celerity/src/language/core/Semantics/Tree/SemanticTree.xml
<Tree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="https://vezel.dev/celerity/SemanticTree"
      xsi:schemaLocation="https://vezel.dev/celerity/SemanticTree ../../../../generators/Semantics/SemanticTree.xsd">
    <!-- Document -->

    <Type Name="Document" Abstract="true" Root="true" />

    <Type Name="ModuleDocument" Base="Document" Root="true">
        <Nodes Name="Attribute" Type="Attribute" />
        <Value Name="Path" Type="ModulePath?" />
        <Nodes Name="Declaration" Type="Declaration" />
    </Type>

    <Type Name="InteractiveDocument" Base="Document" Root="true">
        <Nodes Name="Submission" Type="Submission" />
    </Type>

    <!-- Miscellaneous -->

    <Type Name="Attribute">
        <Computed Name="Name" Type="string" Body="Syntax.NameToken.Text" />
        <Computed Name="Value" Type="object?" Body="Syntax.ValueToken.Value" />
    </Type>

    <Type Name="CodeParameter" Abstract="true">
        <Nodes Name="Attribute" Type="Attribute" />
        <Value Name="Symbol" Type="ParameterSymbol?" />
    </Type>

    <!-- Submissions -->

    <Type Name="Submission" Parent="InteractiveDocument" Abstract="true" />

    <Type Name="DeclarationSubmission" Base="Submission" Parent="InteractiveDocument">
        <Node Name="Declaration" Type="Declaration" />
    </Type>

    <Type Name="StatementSubmission" Base="Submission" Parent="InteractiveDocument">
        <Node Name="Statement" Type="Statement" />
    </Type>

    <!-- Declarations -->

    <Type Name="Declaration" Parent="Document" Abstract="true">
        <Nodes Name="Attribute" Type="Attribute" />
    </Type>

    <Type Name="UseDeclaration" Base="Declaration">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Computed Name="Name" Type="string" Body="Syntax.NameToken.Text" />
        <Value Name="Path" Type="ModulePath?" />
    </Type>

    <Type Name="CodeDeclaration" Base="Declaration" Parent="Document" Abstract="true">
        <Value Name="Symbol" Type="DeclarationSymbol?" />
        <Node Name="Body" Type="Expression" Optional="true" />
    </Type>

    <Type Name="ConstantDeclaration" Base="CodeDeclaration" Parent="Document">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Computed Name="IsPublic" Type="bool" Body="Syntax.PubKeywordToken != null" />
        <Value Name="Symbol" Type="DeclarationSymbol?" Override="true" />
        <Node Name="Body" Type="Expression" Override="true" />
    </Type>

    <Type Name="FunctionDeclaration" Base="CodeDeclaration" Parent="Document">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Computed Name="IsPublic" Type="bool" Body="Syntax.PubKeywordToken != null" />
        <Computed Name="IsExternal" Type="bool" Body="Syntax.ExtKeywordToken != null" />
        <Value Name="Symbol" Type="DeclarationSymbol?" Override="true" />
        <Nodes Name="Parameter" Type="FunctionParameter" />
        <Node Name="Body" Type="BlockExpression" Optional="true" Override="true" />
    </Type>

    <Type Name="FunctionParameter" Base="CodeParameter" Parent="FunctionDeclaration">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Value Name="Symbol" Type="ParameterSymbol?" Override="true" />
    </Type>

    <Type Name="TestDeclaration" Base="CodeDeclaration" Parent="Document">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Value Name="Symbol" Type="DeclarationSymbol?" Override="true" />
        <Node Name="Body" Type="BlockExpression" Override="true" />
    </Type>

    <!-- Statements -->

    <Type Name="Statement" Abstract="true">
        <Nodes Name="Attribute" Type="Attribute" />
    </Type>

    <Type Name="LetStatement" Base="Statement">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Node Name="Pattern" Type="Pattern" />
        <Node Name="Initializer" Type="Expression" />
    </Type>

    <Type Name="DeferStatement" Base="Statement">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Node Name="Expression" Type="Expression" />
    </Type>

    <Type Name="AssertStatement" Base="Statement">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Node Name="Expression" Type="Expression" />
    </Type>

    <Type Name="ExpressionStatement" Base="Statement">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Node Name="Expression" Type="Expression" />
    </Type>

    <!-- Expressions -->

    <Type Name="Expression" Abstract="true" />

    <Type Name="ValueExpression" Base="Expression" Abstract="true" />

    <Type Name="LiteralExpression" Base="ValueExpression">
        <Computed Name="Value" Type="object?" Body="Syntax.LiteralToken.Value" />
    </Type>

    <Type Name="ModuleExpression" Base="ValueExpression">
        <Value Name="Use" Type="UseDeclarationSemantics?" />
        <Value Name="Path" Type="ModulePath" />
    </Type>

    <Type Name="AggregateExpression" Base="ValueExpression" Abstract="true">
        <Node Name="With" Type="Expression" Optional="true" />
        <Nodes Name="Field" Type="AggregateExpressionField" />
    </Type>

    <Type Name="AggregateExpressionField" Parent="AggregateExpression">
        <Computed Name="IsMutable" Type="bool" Body="Syntax.MutKeywordToken != null" />
        <Computed Name="Name" Type="string" Body="Syntax.NameToken.Text" />
        <Node Name="Value" Type="Expression" />
    </Type>

    <Type Name="RecordExpression" Base="AggregateExpression">
        <Node Name="With" Type="Expression" Optional="true" Override="true" />
        <Nodes Name="Field" Type="AggregateExpressionField" Override="true" />
    </Type>

    <Type Name="ErrorExpression" Base="AggregateExpression">
        <Computed Name="Name" Type="string" Body="Syntax.NameToken.Text" />
        <Node Name="With" Type="Expression" Optional="true" Override="true" />
        <Nodes Name="Field" Type="AggregateExpressionField" Override="true" />
    </Type>

    <Type Name="TupleExpression" Base="ValueExpression">
        <Nodes Name="Component" Type="Expression" />
    </Type>

    <Type Name="ArrayExpression" Base="ValueExpression">
        <Computed Name="IsMutable" Type="bool" Body="Syntax.MutKeywordToken != null" />
        <Nodes Name="Element" Type="Expression" />
    </Type>

    <Type Name="SetExpression" Base="ValueExpression">
        <Computed Name="IsMutable" Type="bool" Body="Syntax.MutKeywordToken != null" />
        <Nodes Name="Element" Type="Expression" />
    </Type>

    <Type Name="MapExpression" Base="ValueExpression">
        <Computed Name="IsMutable" Type="bool" Body="Syntax.MutKeywordToken != null" />
        <Nodes Name="Pair" Type="MapExpressionPair" />
    </Type>

    <Type Name="MapExpressionPair" Parent="MapExpression">
        <Node Name="Key" Type="Expression" />
        <Node Name="Value" Type="Expression" />
    </Type>

    <Type Name="LambdaExpression" Base="ValueExpression">
        <Nodes Name="Parameter" Type="LambdaParameter" />
        <Node Name="Body" Type="Expression" />
    </Type>

    <Type Name="LambdaParameter" Base="CodeParameter" Parent="LambdaExpression">
        <Nodes Name="Attribute" Type="Attribute" Override="true" />
        <Value Name="Symbol" Type="ParameterSymbol?" Override="true" />
    </Type>

    <Type Name="OperatorExpression" Base="Expression" Abstract="true" />

    <Type Name="UnaryExpression" Base="OperatorExpression">
        <Node Name="Operand" Type="Expression" />
    </Type>

    <Type Name="BinaryOperatorExpression" Base="OperatorExpression" Abstract="true" />

    <Type Name="AdditiveExpression" Base="BinaryOperatorExpression">
        <Node Name="LeftOperand" Type="Expression" />
        <Node Name="RightOperand" Type="Expression" />
    </Type>

    <Type Name="MultiplicativeExpression" Base="BinaryOperatorExpression">
        <Node Name="LeftOperand" Type="Expression" />
        <Node Name="RightOperand" Type="Expression" />
    </Type>

    <Type Name="BitwiseExpression" Base="BinaryOperatorExpression">
        <Node Name="LeftOperand" Type="Expression" />
        <Node Name="RightOperand" Type="Expression" />
    </Type>

    <Type Name="ShiftExpression" Base="BinaryOperatorExpression">
        <Node Name="LeftOperand" Type="Expression" />
        <Node Name="RightOperand" Type="Expression" />
    </Type>

    <Type Name="LogicalExpression" Base="BinaryOperatorExpression">
        <Node Name="LeftOperand" Type="Expression" />
        <Node Name="RightOperand" Type="Expression" />
    </Type>

    <Type Name="RelationalExpression" Base="BinaryOperatorExpression">
        <Node Name="LeftOperand" Type="Expression" />
        <Node Name="RightOperand" Type="Expression" />
    </Type>

    <Type Name="ControlExpression" Base="Expression" Abstract="true" />

    <Type Name="ConditionalExpression" Base="ControlExpression" Abstract="true" />

    <Type Name="IfExpression" Base="ConditionalExpression">
        <Node Name="Condition" Type="Expression" />
        <Node Name="Body" Type="BlockExpression" />
        <Node Name="Else" Type="BlockExpression" Optional="true" />
    </Type>

    <Type Name="ConditionExpression" Base="ConditionalExpression">
        <Nodes Name="Arm" Type="ConditionExpressionArm" />
    </Type>

    <Type Name="ExpressionArm" Parent="Expression" Abstract="true">
        <Node Name="Body" Type="Expression" />
    </Type>

    <Type Name="ConditionExpressionArm" Base="ExpressionArm" Parent="ConditionExpression">
        <Node Name="Condition" Type="Expression" />
        <Node Name="Body" Type="Expression" Override="true" />
    </Type>

    <Type Name="MatchExpression" Base="ConditionalExpression">
        <Node Name="Operand" Type="Expression" />
        <Nodes Name="Arm" Type="ExpressionPatternArm" />
    </Type>

    <Type Name="ExpressionPatternArm" Base="ExpressionArm">
        <Node Name="Pattern" Type="Pattern" />
